// Phase 7 content seed — Sahabat (male).
// Excludes: abu-bakr-as-shiddiq & umar-bin-khattab (already seeded by 017_demo_figures).
// Production deep-research crawler will enrich biographies.

import { getSeedDb, logSeed } from './_helpers.js'
import { figures, figureCategories, locations } from '../schema/index.js'

type FigureSeed = {
  slug: string
  categorySlug: string
  gender: 'male' | 'female'
  nameFullAr: string
  nameFullId: string
  kunyahAr?: string
  kunyahId?: string
  laqabId?: string
  birthAh?: number
  birthCe?: number
  deathAh?: number
  deathCe?: number
  deathDatePrecision?: 'year' | 'month' | 'day' | 'approximate' | 'range'
  deathCause?: 'natural' | 'martyr' | 'killed' | 'unknown'
  socialCategory?: ('anshar' | 'muhajirin' | 'qurasy' | 'arab_non_qurasy' | 'mawla' | 'non_arab' | 'other')[]
  specialty?: string[]
  rijalGrade?: 'sahabi_udul' | 'thiqah' | 'not_narrator'
  hadithMin?: number
  hadithMax?: number
  primaryLocSlug?: string
  summaryId?: string
}

const FIGURES: FigureSeed[] = [
  // ─── Khulafa ar-Rasyidin (selain Abu Bakr & Umar) ─────────
  {
    slug: 'utsman-bin-affan',
    categorySlug: 'sahabat',
    gender: 'male',
    nameFullAr: 'عثمان بن عفان رضي الله عنه',
    nameFullId: 'Utsman bin Affan RA',
    kunyahAr: 'أبو عبد الله',
    kunyahId: 'Abu Abdullah',
    laqabId: 'Dzun Nurain',
    birthAh: -47,
    birthCe: 576,
    deathAh: 35,
    deathCe: 656,
    deathDatePrecision: 'year',
    deathCause: 'killed',
    socialCategory: ['muhajirin', 'qurasy'],
    specialty: ['hadith'],
    rijalGrade: 'sahabi_udul',
    hadithMin: 146,
    hadithMax: 146,
    primaryLocSlug: 'madinah',
    summaryId: 'Khalifah ketiga, dijuluki Dzun Nurain karena menikahi dua putri Nabi ﷺ. Pengumpul mushaf utsmani.',
  },
  {
    slug: 'ali-bin-abi-thalib',
    categorySlug: 'sahabat',
    gender: 'male',
    nameFullAr: 'علي بن أبي طالب رضي الله عنه',
    nameFullId: 'Ali bin Abi Thalib RA',
    kunyahAr: 'أبو الحسن',
    kunyahId: 'Abu al-Hasan',
    laqabId: 'Abu Turab, Karramallahu Wajhah',
    birthAh: -10,
    birthCe: 600,
    deathAh: 40,
    deathCe: 661,
    deathDatePrecision: 'year',
    deathCause: 'killed',
    socialCategory: ['muhajirin', 'qurasy'],
    specialty: ['hadith', 'fiqh', 'tafsir'],
    rijalGrade: 'sahabi_udul',
    hadithMin: 586,
    hadithMax: 586,
    primaryLocSlug: 'kufah',
    summaryId: 'Khalifah keempat, sepupu sekaligus menantu Nabi ﷺ. Pemuda pertama yang masuk Islam.',
  },

  // ─── Asyrah Mubasysharah (6 sisanya) ──────────────────────
  {
    slug: 'thalhah-bin-ubaidillah',
    categorySlug: 'sahabat',
    gender: 'male',
    nameFullAr: 'طلحة بن عبيد الله رضي الله عنه',
    nameFullId: 'Thalhah bin Ubaidillah RA',
    kunyahAr: 'أبو محمد',
    kunyahId: 'Abu Muhammad',
    laqabId: 'Thalhatul Khair',
    birthAh: -28,
    birthCe: 596,
    deathAh: 36,
    deathCe: 656,
    deathDatePrecision: 'year',
    deathCause: 'martyr',
    socialCategory: ['muhajirin', 'qurasy'],
    specialty: ['hadith'],
    rijalGrade: 'sahabi_udul',
    hadithMin: 38,
    hadithMax: 38,
    primaryLocSlug: 'madinah',
    summaryId: 'Salah satu sepuluh sahabat yang dijanjikan surga. Syahid pada Perang Jamal.',
  },
  {
    slug: 'zubair-bin-awwam',
    categorySlug: 'sahabat',
    gender: 'male',
    nameFullAr: 'الزبير بن العوام رضي الله عنه',
    nameFullId: 'Zubair bin Awwam RA',
    kunyahAr: 'أبو عبد الله',
    kunyahId: 'Abu Abdullah',
    laqabId: 'Hawari Rasulillah',
    birthAh: -28,
    birthCe: 594,
    deathAh: 36,
    deathCe: 656,
    deathDatePrecision: 'year',
    deathCause: 'killed',
    socialCategory: ['muhajirin', 'qurasy'],
    specialty: ['hadith'],
    rijalGrade: 'sahabi_udul',
    hadithMin: 38,
    hadithMax: 38,
    primaryLocSlug: 'madinah',
    summaryId: 'Hawari (pembela) Rasulullah ﷺ, suami Asma binti Abu Bakr. Termasuk Asyrah Mubasysyarah.',
  },
  {
    slug: 'abdurrahman-bin-auf',
    categorySlug: 'sahabat',
    gender: 'male',
    nameFullAr: 'عبد الرحمن بن عوف رضي الله عنه',
    nameFullId: 'Abdurrahman bin Auf RA',
    kunyahAr: 'أبو محمد',
    kunyahId: 'Abu Muhammad',
    birthAh: -43,
    birthCe: 580,
    deathAh: 32,
    deathCe: 652,
    deathDatePrecision: 'year',
    deathCause: 'natural',
    socialCategory: ['muhajirin', 'qurasy'],
    specialty: ['hadith'],
    rijalGrade: 'sahabi_udul',
    hadithMin: 65,
    hadithMax: 65,
    primaryLocSlug: 'madinah',
    summaryId: 'Saudagar kaya raya yang dermawan, termasuk Asyrah Mubasysyarah. Anggota syura penunjukan khalifah pasca Umar.',
  },
  {
    slug: 'saad-bin-abi-waqqash',
    categorySlug: 'sahabat',
    gender: 'male',
    nameFullAr: 'سعد بن أبي وقاص رضي الله عنه',
    nameFullId: "Sa'ad bin Abi Waqqash RA",
    kunyahAr: 'أبو إسحاق',
    kunyahId: 'Abu Ishaq',
    birthAh: -23,
    birthCe: 600,
    deathAh: 55,
    deathCe: 675,
    deathDatePrecision: 'year',
    deathCause: 'natural',
    socialCategory: ['muhajirin', 'qurasy'],
    specialty: ['hadith'],
    rijalGrade: 'sahabi_udul',
    hadithMin: 271,
    hadithMax: 271,
    primaryLocSlug: 'kufah',
    summaryId: 'Panglima Perang Qadisiyyah, penakluk Persia. Termasuk Asyrah Mubasysyarah.',
  },
  {
    slug: 'said-bin-zaid',
    categorySlug: 'sahabat',
    gender: 'male',
    nameFullAr: 'سعيد بن زيد رضي الله عنه',
    nameFullId: "Sa'id bin Zaid RA",
    kunyahAr: 'أبو الأعور',
    kunyahId: 'Abu al-A\'war',
    birthAh: -22,
    birthCe: 600,
    deathAh: 51,
    deathCe: 671,
    deathDatePrecision: 'year',
    deathCause: 'natural',
    socialCategory: ['muhajirin', 'qurasy'],
    specialty: ['hadith'],
    rijalGrade: 'sahabi_udul',
    hadithMin: 48,
    hadithMax: 48,
    primaryLocSlug: 'madinah',
    summaryId: 'Sepupu Umar bin Khattab, masuk Islam sangat awal. Termasuk Asyrah Mubasysyarah.',
  },
  {
    slug: 'abu-ubaidah-bin-jarrah',
    categorySlug: 'sahabat',
    gender: 'male',
    nameFullAr: 'أبو عبيدة بن الجراح رضي الله عنه',
    nameFullId: 'Abu Ubaidah bin al-Jarrah RA',
    kunyahAr: 'أبو عبيدة',
    kunyahId: 'Abu Ubaidah',
    laqabId: 'Amin al-Ummah',
    birthAh: -40,
    birthCe: 583,
    deathAh: 18,
    deathCe: 639,
    deathDatePrecision: 'year',
    deathCause: 'natural',
    socialCategory: ['muhajirin', 'qurasy'],
    specialty: ['hadith'],
    rijalGrade: 'sahabi_udul',
    hadithMin: 14,
    hadithMax: 14,
    primaryLocSlug: 'damascus',
    summaryId: 'Dijuluki Nabi ﷺ sebagai "Amin al-Ummah". Panglima Sham, wafat akibat wabah Amwas.',
  },

  // ─── Sahabat penting lain ─────────────────────────────────
  {
    slug: 'hamzah-bin-abdul-muthalib',
    categorySlug: 'sahabat',
    gender: 'male',
    nameFullAr: 'حمزة بن عبد المطلب رضي الله عنه',
    nameFullId: 'Hamzah bin Abdul Muthalib RA',
    kunyahAr: 'أبو عمارة',
    kunyahId: 'Abu Umarah',
    laqabId: 'Asadullah, Sayyidusy Syuhada',
    birthAh: -54,
    birthCe: 568,
    deathAh: 3,
    deathCe: 625,
    deathDatePrecision: 'year',
    deathCause: 'martyr',
    socialCategory: ['muhajirin', 'qurasy'],
    rijalGrade: 'sahabi_udul',
    primaryLocSlug: 'madinah',
    summaryId: 'Paman Nabi ﷺ, dijuluki "Singa Allah". Syahid pada Perang Uhud tahun 3 H.',
  },
  {
    slug: 'abbas-bin-abdul-muthalib',
    categorySlug: 'sahabat',
    gender: 'male',
    nameFullAr: 'العباس بن عبد المطلب رضي الله عنه',
    nameFullId: 'Abbas bin Abdul Muthalib RA',
    kunyahAr: 'أبو الفضل',
    kunyahId: 'Abu al-Fadhl',
    birthAh: -56,
    birthCe: 568,
    deathAh: 32,
    deathCe: 653,
    deathDatePrecision: 'year',
    deathCause: 'natural',
    socialCategory: ['muhajirin', 'qurasy'],
    specialty: ['hadith'],
    rijalGrade: 'sahabi_udul',
    hadithMin: 35,
    hadithMax: 35,
    primaryLocSlug: 'madinah',
    summaryId: 'Paman Nabi ﷺ, leluhur Bani Abbas yang kelak mendirikan Khilafah Abbasiyah.',
  },
  {
    slug: 'bilal-bin-rabah',
    categorySlug: 'sahabat',
    gender: 'male',
    nameFullAr: 'بلال بن رباح رضي الله عنه',
    nameFullId: 'Bilal bin Rabah RA',
    kunyahAr: 'أبو عبد الله',
    kunyahId: 'Abu Abdullah',
    laqabId: 'Muadzin Rasulullah',
    birthAh: -43,
    birthCe: 580,
    deathAh: 20,
    deathCe: 641,
    deathDatePrecision: 'year',
    deathCause: 'natural',
    socialCategory: ['muhajirin', 'mawla'],
    specialty: ['hadith'],
    rijalGrade: 'sahabi_udul',
    hadithMin: 44,
    hadithMax: 44,
    primaryLocSlug: 'damascus',
    summaryId: 'Muadzin pertama dalam Islam, mawla Abu Bakr yang dibebaskan setelah disiksa karena imannya.',
  },
  {
    slug: 'salman-al-farisi',
    categorySlug: 'sahabat',
    gender: 'male',
    nameFullAr: 'سلمان الفارسي رضي الله عنه',
    nameFullId: 'Salman al-Farisi RA',
    kunyahAr: 'أبو عبد الله',
    kunyahId: 'Abu Abdullah',
    deathAh: 35,
    deathCe: 656,
    deathDatePrecision: 'year',
    deathCause: 'natural',
    socialCategory: ['non_arab', 'mawla'],
    specialty: ['hadith'],
    rijalGrade: 'sahabi_udul',
    hadithMin: 60,
    hadithMax: 60,
    primaryLocSlug: 'ctesiphon',
    summaryId: 'Sahabat dari Persia, pencetus strategi parit pada Perang Khandaq. "Salman minna Ahlul Bait".',
  },
  {
    slug: 'mush-ab-bin-umair',
    categorySlug: 'sahabat',
    gender: 'male',
    nameFullAr: 'مصعب بن عمير رضي الله عنه',
    nameFullId: "Mush'ab bin Umair RA",
    kunyahAr: 'أبو عبد الله',
    kunyahId: 'Abu Abdullah',
    birthAh: -31,
    birthCe: 594,
    deathAh: 3,
    deathCe: 625,
    deathDatePrecision: 'year',
    deathCause: 'martyr',
    socialCategory: ['muhajirin', 'qurasy'],
    rijalGrade: 'sahabi_udul',
    primaryLocSlug: 'madinah',
    summaryId: 'Duta Islam pertama ke Madinah. Syahid pada Perang Uhud sambil memegang panji Rasulullah ﷺ.',
  },
  {
    slug: 'khalid-bin-walid',
    categorySlug: 'sahabat',
    gender: 'male',
    nameFullAr: 'خالد بن الوليد رضي الله عنه',
    nameFullId: 'Khalid bin Walid RA',
    kunyahAr: 'أبو سليمان',
    kunyahId: 'Abu Sulaiman',
    laqabId: 'Saifullah al-Maslul',
    birthAh: -30,
    birthCe: 592,
    deathAh: 21,
    deathCe: 642,
    deathDatePrecision: 'year',
    deathCause: 'natural',
    socialCategory: ['muhajirin', 'qurasy'],
    specialty: ['hadith'],
    rijalGrade: 'sahabi_udul',
    hadithMin: 18,
    hadithMax: 18,
    primaryLocSlug: 'hims',
    summaryId: 'Panglima besar, "Pedang Allah yang Terhunus". Penakluk Sham pada Perang Yarmuk.',
  },
  {
    slug: 'amr-bin-ash',
    categorySlug: 'sahabat',
    gender: 'male',
    nameFullAr: 'عمرو بن العاص رضي الله عنه',
    nameFullId: 'Amr bin Ash RA',
    kunyahAr: 'أبو عبد الله',
    kunyahId: 'Abu Abdullah',
    birthAh: -50,
    birthCe: 573,
    deathAh: 43,
    deathCe: 664,
    deathDatePrecision: 'year',
    deathCause: 'natural',
    socialCategory: ['muhajirin', 'qurasy'],
    specialty: ['hadith'],
    rijalGrade: 'sahabi_udul',
    hadithMin: 39,
    hadithMax: 39,
    primaryLocSlug: 'fustat',
    summaryId: 'Penakluk Mesir, pendiri kota Fustat. Salah satu tokoh diplomat ulung di masa Nabi ﷺ.',
  },
  {
    slug: 'abdullah-bin-masud',
    categorySlug: 'sahabat',
    gender: 'male',
    nameFullAr: 'عبد الله بن مسعود رضي الله عنه',
    nameFullId: "Abdullah bin Mas'ud RA",
    kunyahAr: 'أبو عبد الرحمن',
    kunyahId: 'Abu Abdurrahman',
    birthAh: -34,
    birthCe: 590,
    deathAh: 32,
    deathCe: 653,
    deathDatePrecision: 'year',
    deathCause: 'natural',
    socialCategory: ['muhajirin'],
    specialty: ['hadith', 'tafsir', 'qira-ah', 'fiqh'],
    rijalGrade: 'sahabi_udul',
    hadithMin: 848,
    hadithMax: 848,
    primaryLocSlug: 'kufah',
    summaryId: 'Ahli Al-Quran, salah satu dari empat sahabat yang dianjurkan Nabi ﷺ untuk diambil ilmu Quran-nya.',
  },
  {
    slug: 'muadz-bin-jabal',
    categorySlug: 'sahabat',
    gender: 'male',
    nameFullAr: 'معاذ بن جبل رضي الله عنه',
    nameFullId: "Mu'adz bin Jabal RA",
    kunyahAr: 'أبو عبد الرحمن',
    kunyahId: 'Abu Abdurrahman',
    birthAh: -20,
    birthCe: 603,
    deathAh: 18,
    deathCe: 639,
    deathDatePrecision: 'year',
    deathCause: 'natural',
    socialCategory: ['anshar'],
    specialty: ['hadith', 'fiqh'],
    rijalGrade: 'sahabi_udul',
    hadithMin: 157,
    hadithMax: 157,
    primaryLocSlug: 'yarmuk',
    summaryId: 'Paling tahu tentang halal-haram, diutus Nabi ﷺ ke Yaman. Wafat akibat wabah Amwas.',
  },
  {
    slug: 'ubay-bin-kaab',
    categorySlug: 'sahabat',
    gender: 'male',
    nameFullAr: 'أبي بن كعب رضي الله عنه',
    nameFullId: "Ubay bin Ka'b RA",
    kunyahAr: 'أبو المنذر',
    kunyahId: 'Abu al-Mundzir',
    laqabId: 'Sayyidul Qurra',
    deathAh: 30,
    deathCe: 650,
    deathDatePrecision: 'year',
    deathCause: 'natural',
    socialCategory: ['anshar'],
    specialty: ['hadith', 'tafsir', 'qira-ah'],
    rijalGrade: 'sahabi_udul',
    hadithMin: 164,
    hadithMax: 164,
    primaryLocSlug: 'madinah',
    summaryId: 'Pemimpin para qari, salah satu pengumpul Al-Quran di masa Nabi ﷺ.',
  },
  {
    slug: 'zayd-bin-tsabit',
    categorySlug: 'sahabat',
    gender: 'male',
    nameFullAr: 'زيد بن ثابت رضي الله عنه',
    nameFullId: 'Zaid bin Tsabit RA',
    kunyahAr: 'أبو سعيد',
    kunyahId: 'Abu Sa\'id',
    birthAh: -11,
    birthCe: 611,
    deathAh: 45,
    deathCe: 665,
    deathDatePrecision: 'year',
    deathCause: 'natural',
    socialCategory: ['anshar'],
    specialty: ['hadith', 'fiqh', 'fara-id'],
    rijalGrade: 'sahabi_udul',
    hadithMin: 92,
    hadithMax: 92,
    primaryLocSlug: 'madinah',
    summaryId: 'Penulis wahyu Nabi ﷺ dan kompiler mushaf Al-Quran di masa Abu Bakr dan Utsman.',
  },
  {
    slug: 'abdullah-bin-abbas',
    categorySlug: 'sahabat',
    gender: 'male',
    nameFullAr: 'عبد الله بن عباس رضي الله عنه',
    nameFullId: 'Abdullah bin Abbas RA',
    kunyahAr: 'أبو العباس',
    kunyahId: 'Abu al-Abbas',
    laqabId: 'Habrul Ummah, Turjumanul Quran',
    birthAh: -3,
    birthCe: 619,
    deathAh: 68,
    deathCe: 687,
    deathDatePrecision: 'year',
    deathCause: 'natural',
    socialCategory: ['muhajirin', 'qurasy'],
    specialty: ['hadith', 'tafsir', 'fiqh'],
    rijalGrade: 'sahabi_udul',
    hadithMin: 1660,
    hadithMax: 1660,
    primaryLocSlug: 'thaif',
    summaryId: 'Sepupu Nabi ﷺ, "Tinta Umat" dan penerjemah Al-Quran. Didoakan Nabi ﷺ agar dipahamkan agama.',
  },
  {
    slug: 'abdullah-bin-umar',
    categorySlug: 'sahabat',
    gender: 'male',
    nameFullAr: 'عبد الله بن عمر رضي الله عنه',
    nameFullId: 'Abdullah bin Umar RA',
    kunyahAr: 'أبو عبد الرحمن',
    kunyahId: 'Abu Abdurrahman',
    birthAh: -10,
    birthCe: 612,
    deathAh: 73,
    deathCe: 693,
    deathDatePrecision: 'year',
    deathCause: 'natural',
    socialCategory: ['muhajirin', 'qurasy'],
    specialty: ['hadith', 'fiqh'],
    rijalGrade: 'sahabi_udul',
    hadithMin: 2630,
    hadithMax: 2630,
    primaryLocSlug: 'makkah',
    summaryId: 'Putra Umar bin Khattab, sangat berhati-hati dalam ittiba Sunnah Nabi ﷺ.',
  },
  {
    slug: 'abdullah-bin-amr-bin-ash',
    categorySlug: 'sahabat',
    gender: 'male',
    nameFullAr: 'عبد الله بن عمرو بن العاص رضي الله عنه',
    nameFullId: 'Abdullah bin Amr bin Ash RA',
    kunyahAr: 'أبو محمد',
    kunyahId: 'Abu Muhammad',
    birthAh: -27,
    birthCe: 597,
    deathAh: 65,
    deathCe: 684,
    deathDatePrecision: 'year',
    deathCause: 'natural',
    socialCategory: ['muhajirin', 'qurasy'],
    specialty: ['hadith'],
    rijalGrade: 'sahabi_udul',
    hadithMin: 700,
    hadithMax: 700,
    primaryLocSlug: 'fustat',
    summaryId: 'Putra Amr bin Ash, sahabat pencatat hadits dari Nabi ﷺ ("Ash-Shahifah ash-Shadiqah").',
  },
  {
    slug: 'anas-bin-malik',
    categorySlug: 'sahabat',
    gender: 'male',
    nameFullAr: 'أنس بن مالك رضي الله عنه',
    nameFullId: 'Anas bin Malik RA',
    kunyahAr: 'أبو حمزة',
    kunyahId: 'Abu Hamzah',
    birthAh: -10,
    birthCe: 612,
    deathAh: 93,
    deathCe: 712,
    deathDatePrecision: 'year',
    deathCause: 'natural',
    socialCategory: ['anshar'],
    specialty: ['hadith'],
    rijalGrade: 'sahabi_udul',
    hadithMin: 2286,
    hadithMax: 2286,
    primaryLocSlug: 'bashrah',
    summaryId: 'Pelayan Nabi ﷺ selama 10 tahun di Madinah. Salah satu sahabat dengan riwayat hadits terbanyak.',
  },
  {
    slug: 'abu-hurairah',
    categorySlug: 'sahabat',
    gender: 'male',
    nameFullAr: 'أبو هريرة رضي الله عنه',
    nameFullId: 'Abu Hurairah RA',
    kunyahAr: 'أبو هريرة',
    kunyahId: 'Abu Hurairah',
    birthAh: -19,
    birthCe: 603,
    deathAh: 59,
    deathCe: 679,
    deathDatePrecision: 'year',
    deathCause: 'natural',
    socialCategory: ['arab_non_qurasy'],
    specialty: ['hadith'],
    rijalGrade: 'sahabi_udul',
    hadithMin: 5374,
    hadithMax: 5374,
    primaryLocSlug: 'madinah',
    summaryId: 'Nama aslinya Abdurrahman bin Shakhr ad-Dausi. Periwayat hadits terbanyak (5374 hadits).',
  },
  {
    slug: 'abu-said-al-khudri',
    categorySlug: 'sahabat',
    gender: 'male',
    nameFullAr: 'أبو سعيد الخدري رضي الله عنه',
    nameFullId: "Abu Sa'id al-Khudri RA",
    kunyahAr: 'أبو سعيد',
    kunyahId: 'Abu Sa\'id',
    birthAh: -10,
    birthCe: 612,
    deathAh: 74,
    deathCe: 693,
    deathDatePrecision: 'year',
    deathCause: 'natural',
    socialCategory: ['anshar'],
    specialty: ['hadith', 'fiqh'],
    rijalGrade: 'sahabi_udul',
    hadithMin: 1170,
    hadithMax: 1170,
    primaryLocSlug: 'madinah',
    summaryId: 'Nama aslinya Sa\'ad bin Malik. Sahabat Anshar muda yang banyak meriwayatkan hadits.',
  },
  {
    slug: 'jabir-bin-abdullah',
    categorySlug: 'sahabat',
    gender: 'male',
    nameFullAr: 'جابر بن عبد الله رضي الله عنه',
    nameFullId: 'Jabir bin Abdullah RA',
    kunyahAr: 'أبو عبد الله',
    kunyahId: 'Abu Abdullah',
    birthAh: -16,
    birthCe: 607,
    deathAh: 78,
    deathCe: 697,
    deathDatePrecision: 'year',
    deathCause: 'natural',
    socialCategory: ['anshar'],
    specialty: ['hadith', 'fiqh'],
    rijalGrade: 'sahabi_udul',
    hadithMin: 1540,
    hadithMax: 1540,
    primaryLocSlug: 'madinah',
    summaryId: 'Sahabat Anshar dari Bani Salimah, periwayat haji wada Nabi ﷺ secara terperinci.',
  },
  {
    slug: 'sa-ad-bin-muadz',
    categorySlug: 'sahabat',
    gender: 'male',
    nameFullAr: 'سعد بن معاذ رضي الله عنه',
    nameFullId: "Sa'ad bin Mu'adz RA",
    kunyahAr: 'أبو عمرو',
    kunyahId: 'Abu Amr',
    birthAh: -32,
    birthCe: 591,
    deathAh: 5,
    deathCe: 627,
    deathDatePrecision: 'year',
    deathCause: 'martyr',
    socialCategory: ['anshar'],
    rijalGrade: 'sahabi_udul',
    primaryLocSlug: 'madinah',
    summaryId: 'Pemimpin suku Aus. Wafat akibat luka Perang Khandaq, Arsy berguncang karenanya.',
  },
  {
    slug: 'usaid-bin-hudair',
    categorySlug: 'sahabat',
    gender: 'male',
    nameFullAr: 'أسيد بن حضير رضي الله عنه',
    nameFullId: 'Usaid bin Hudhair RA',
    kunyahAr: 'أبو يحيى',
    kunyahId: 'Abu Yahya',
    deathAh: 20,
    deathCe: 641,
    deathDatePrecision: 'year',
    deathCause: 'natural',
    socialCategory: ['anshar'],
    specialty: ['hadith'],
    rijalGrade: 'sahabi_udul',
    hadithMin: 18,
    hadithMax: 18,
    primaryLocSlug: 'madinah',
    summaryId: 'Pemimpin Anshar dari Bani Abdul Asyhal, salah satu naqib di Baiat Aqabah kedua.',
  },
  {
    slug: 'abu-darda',
    categorySlug: 'sahabat',
    gender: 'male',
    nameFullAr: 'أبو الدرداء رضي الله عنه',
    nameFullId: 'Abu Darda RA',
    kunyahAr: 'أبو الدرداء',
    kunyahId: 'Abu Darda',
    deathAh: 32,
    deathCe: 652,
    deathDatePrecision: 'year',
    deathCause: 'natural',
    socialCategory: ['anshar'],
    specialty: ['hadith', 'fiqh', 'qira-ah'],
    rijalGrade: 'sahabi_udul',
    hadithMin: 179,
    hadithMax: 179,
    primaryLocSlug: 'damascus',
    summaryId: 'Nama aslinya Uwaimir bin Zaid. Hakim dan qari Damaskus, dikenal sebagai ahli hikmah.',
  },
  {
    slug: 'hudzaifah-bin-yaman',
    categorySlug: 'sahabat',
    gender: 'male',
    nameFullAr: 'حذيفة بن اليمان رضي الله عنه',
    nameFullId: 'Hudzaifah bin al-Yaman RA',
    kunyahAr: 'أبو عبد الله',
    kunyahId: 'Abu Abdullah',
    laqabId: 'Shahibu Sirri Rasulillah',
    deathAh: 36,
    deathCe: 656,
    deathDatePrecision: 'year',
    deathCause: 'natural',
    socialCategory: ['muhajirin'],
    specialty: ['hadith'],
    rijalGrade: 'sahabi_udul',
    hadithMin: 225,
    hadithMax: 225,
    primaryLocSlug: 'kufah',
    summaryId: 'Pemegang rahasia Nabi ﷺ tentang nama-nama munafik. Penakluk Nahawand.',
  },
]

export async function seed021SahabatMale() {
  const db = getSeedDb()
  const cats = await db.select().from(figureCategories)
  const catBySlug = new Map(cats.map((c) => [c.slug, c.id]))
  const locs = await db.select().from(locations)
  const locBySlug = new Map(locs.map((l) => [l.slug, l.id]))

  let total = 0
  for (const f of FIGURES) {
    const categoryId = catBySlug.get(f.categorySlug)
    if (!categoryId) continue
    const primaryLocationId = f.primaryLocSlug ? locBySlug.get(f.primaryLocSlug) : undefined
    const result = await db
      .insert(figures)
      .values({
        slug: f.slug,
        categoryId,
        gender: f.gender,
        nameFullAr: f.nameFullAr,
        nameFullId: f.nameFullId,
        kunyahAr: f.kunyahAr,
        kunyahId: f.kunyahId,
        laqabId: f.laqabId,
        birthDateAh: f.birthAh,
        birthDateCe: f.birthCe,
        deathDateAh: f.deathAh,
        deathDateCe: f.deathCe,
        deathDatePrecision: f.deathDatePrecision ?? 'year',
        deathCause: f.deathCause,
        socialCategory: f.socialCategory,
        specialty: f.specialty,
        rijalGrade: f.rijalGrade ?? 'sahabi_udul',
        hadithCountMin: f.hadithMin,
        hadithCountMax: f.hadithMax,
        primaryLocationId,
        summaryId: f.summaryId,
        status: 'published',
        publishedAt: new Date(),
      })
      .onConflictDoNothing()
      .returning()
    if (result.length > 0) total++
  }
  logSeed('sahabat_male', total)
}
