// Phase 7 content seed: Ulama pasca-salaf (di luar generasi sahabat/tabi'in/tabi'ut-tabi'in).
// Pattern mirrors 017_demo_figures.ts.
// Per IDEAS sec. 2.0b/2.0c: only deceased ulama (no still-alive figures).
// Idempotent via onConflictDoNothing on figures.slug.

import { getSeedDb, logSeed } from './_helpers.js'
import { figures, figureCategories, locations } from '../schema/index.js'

type DatePrecision = 'year' | 'month' | 'day' | 'approximate' | 'range'
type Madhab = 'shafii' | 'maliki' | 'hanafi' | 'hanbali' | 'zhahiri' | 'no_madhab'

type FigureSeed = {
  slug: string
  categorySlug: string
  gender: 'male' | 'female'
  nameFullAr: string
  nameFullId: string
  kunyahAr?: string
  laqabId?: string
  birthAh?: number
  birthCe?: number
  birthPrecision?: DatePrecision
  deathAh?: number
  deathCe?: number
  deathPrecision?: DatePrecision
  specialty?: string[]
  madhab?: Madhab
  rijalGrade?: 'thiqah' | 'not_narrator'
  primaryLocSlug?: string
  summaryId?: string
}

const FIGURES: FigureSeed[] = [
  // ─── Era Klasik (4-5 H) ────────────────────────────────────
  {
    slug: 'ibn-abi-hatim-ar-razi',
    categorySlug: 'shalih_pasca_rasul',
    gender: 'male',
    nameFullAr: 'ابن أبي حاتم الرازي رحمه الله',
    nameFullId: 'Ibn Abi Hatim ar-Razi rahimahullah',
    kunyahAr: 'أبو محمد',
    birthAh: 240,
    birthCe: 854,
    birthPrecision: 'approximate',
    deathAh: 327,
    deathCe: 938,
    deathPrecision: 'year',
    specialty: ['hadith', 'rijal', 'tafsir'],
    madhab: 'shafii',
    rijalGrade: 'thiqah',
    summaryId: 'Ulama hadits & kritikus rijal terkemuka. Karya: "al-Jarh wat-Ta\'dil" — referensi utama ilmu rijal.',
  },
  {
    slug: 'at-tabari',
    categorySlug: 'shalih_pasca_rasul',
    gender: 'male',
    nameFullAr: 'محمد بن جرير الطبري رحمه الله',
    nameFullId: 'Muhammad bin Jarir at-Tabari rahimahullah',
    kunyahAr: 'أبو جعفر',
    laqabId: 'Imam al-Mufassirin',
    birthAh: 224,
    birthCe: 839,
    birthPrecision: 'year',
    deathAh: 310,
    deathCe: 923,
    deathPrecision: 'year',
    specialty: ['tafsir', 'tarikh', 'fiqh', 'hadith'],
    madhab: 'no_madhab',
    rijalGrade: 'thiqah',
    summaryId: 'Imam ahli tafsir & sejarawan. Karya: "Jami\' al-Bayan" (Tafsir at-Tabari) & "Tarikh al-Umam wal-Muluk".',
  },
  {
    slug: 'ibn-hibban',
    categorySlug: 'shalih_pasca_rasul',
    gender: 'male',
    nameFullAr: 'محمد بن حبان البستي رحمه الله',
    nameFullId: 'Muhammad bin Hibban al-Busti rahimahullah',
    kunyahAr: 'أبو حاتم',
    birthAh: 270,
    birthCe: 884,
    birthPrecision: 'approximate',
    deathAh: 354,
    deathCe: 965,
    deathPrecision: 'year',
    specialty: ['hadith', 'rijal'],
    madhab: 'shafii',
    rijalGrade: 'thiqah',
    summaryId: 'Kompilator "Sahih Ibn Hibban" & "ats-Tsiqat". Termasuk kompilator kitab sahih ketiga setelah Bukhari & Muslim.',
  },
  {
    slug: 'al-hakim-an-naysaburi',
    categorySlug: 'shalih_pasca_rasul',
    gender: 'male',
    nameFullAr: 'الحاكم النيسابوري رحمه الله',
    nameFullId: 'al-Hakim an-Naysaburi rahimahullah',
    kunyahAr: 'أبو عبد الله',
    birthAh: 321,
    birthCe: 933,
    birthPrecision: 'year',
    deathAh: 405,
    deathCe: 1014,
    deathPrecision: 'year',
    specialty: ['hadith', 'rijal'],
    madhab: 'shafii',
    rijalGrade: 'thiqah',
    summaryId: 'Hafizh hadits dari Nisapur. Karya: "al-Mustadrak \'ala ash-Shahihain" & "Ma\'rifat \'Ulum al-Hadits".',
  },
  {
    slug: 'al-baihaqi',
    categorySlug: 'shalih_pasca_rasul',
    gender: 'male',
    nameFullAr: 'أبو بكر البيهقي رحمه الله',
    nameFullId: 'Abu Bakr al-Baihaqi rahimahullah',
    kunyahAr: 'أبو بكر',
    birthAh: 384,
    birthCe: 994,
    birthPrecision: 'year',
    deathAh: 458,
    deathCe: 1066,
    deathPrecision: 'year',
    specialty: ['hadith', 'fiqh', 'aqidah'],
    madhab: 'shafii',
    rijalGrade: 'thiqah',
    summaryId: 'Imam hadits madzhab Syafi\'i. Karya: "as-Sunan al-Kubra", "Syu\'ab al-Iman", & "Dala\'il an-Nubuwwah".',
  },
  {
    slug: 'al-khatib-al-baghdadi',
    categorySlug: 'shalih_pasca_rasul',
    gender: 'male',
    nameFullAr: 'الخطيب البغدادي رحمه الله',
    nameFullId: 'al-Khatib al-Baghdadi rahimahullah',
    kunyahAr: 'أبو بكر',
    birthAh: 392,
    birthCe: 1002,
    birthPrecision: 'year',
    deathAh: 463,
    deathCe: 1071,
    deathPrecision: 'year',
    specialty: ['hadith', 'rijal', 'tarikh'],
    madhab: 'shafii',
    rijalGrade: 'thiqah',
    primaryLocSlug: 'baghdad',
    summaryId: 'Sejarawan & muhaddits Baghdad. Karya monumental: "Tarikh Baghdad" — biografi ribuan ulama Baghdad.',
  },
  {
    slug: 'ibn-abdil-barr',
    categorySlug: 'shalih_pasca_rasul',
    gender: 'male',
    nameFullAr: 'ابن عبد البر القرطبي رحمه الله',
    nameFullId: 'Ibn Abdil Barr al-Qurthubi rahimahullah',
    kunyahAr: 'أبو عمر',
    birthAh: 368,
    birthCe: 978,
    birthPrecision: 'year',
    deathAh: 463,
    deathCe: 1071,
    deathPrecision: 'year',
    specialty: ['fiqh', 'hadith', 'rijal'],
    madhab: 'maliki',
    rijalGrade: 'thiqah',
    summaryId: 'Hafizh Andalusia. Karya: "al-Isti\'ab fi Ma\'rifat al-Ashhab" — biografi sahabat — & "at-Tamhid".',
  },

  // ─── Era Klasik Lanjutan (5-7 H) ───────────────────────────
  {
    slug: 'imam-ghazali',
    categorySlug: 'shalih_pasca_rasul',
    gender: 'male',
    nameFullAr: 'أبو حامد الغزالي رحمه الله',
    nameFullId: 'Abu Hamid al-Ghazali rahimahullah',
    kunyahAr: 'أبو حامد',
    laqabId: 'Hujjatul Islam',
    birthAh: 450,
    birthCe: 1058,
    birthPrecision: 'year',
    deathAh: 505,
    deathCe: 1111,
    deathPrecision: 'year',
    specialty: ['fiqh', 'ushul', 'tasawuf', 'mantiq'],
    madhab: 'shafii',
    rijalGrade: 'not_narrator',
    summaryId: 'Ulama besar madzhab Syafi\'i, gelar "Hujjatul Islam". Karya: "Ihya\' \'Ulum ad-Din" & "al-Mustashfa".',
  },
  {
    slug: 'al-qadhi-iyadh',
    categorySlug: 'shalih_pasca_rasul',
    gender: 'male',
    nameFullAr: 'القاضي عياض اليحصبي رحمه الله',
    nameFullId: 'al-Qadhi Iyadh al-Yahsubi rahimahullah',
    kunyahAr: 'أبو الفضل',
    birthAh: 476,
    birthCe: 1083,
    birthPrecision: 'year',
    deathAh: 544,
    deathCe: 1149,
    deathPrecision: 'year',
    specialty: ['hadith', 'fiqh', 'sirah'],
    madhab: 'maliki',
    rijalGrade: 'thiqah',
    summaryId: 'Hakim & ulama Maliki dari Maghrib. Karya: "asy-Syifa bi Ta\'rif Huquq al-Mushthafa" — kitab sirah & hak Nabi ﷺ.',
  },
  {
    slug: 'ibn-asakir',
    categorySlug: 'shalih_pasca_rasul',
    gender: 'male',
    nameFullAr: 'ابن عساكر الدمشقي رحمه الله',
    nameFullId: 'Ibn Asakir ad-Dimasyqi rahimahullah',
    kunyahAr: 'أبو القاسم',
    birthAh: 499,
    birthCe: 1105,
    birthPrecision: 'year',
    deathAh: 571,
    deathCe: 1176,
    deathPrecision: 'year',
    specialty: ['hadith', 'tarikh', 'rijal'],
    madhab: 'shafii',
    rijalGrade: 'thiqah',
    primaryLocSlug: 'damaskus',
    summaryId: 'Sejarawan Damaskus. Karya monumental: "Tarikh Dimasyq" — 80 jilid biografi ulama & tokoh Syam.',
  },
  {
    slug: 'ibn-jawzi',
    categorySlug: 'shalih_pasca_rasul',
    gender: 'male',
    nameFullAr: 'ابن الجوزي رحمه الله',
    nameFullId: 'Ibn al-Jauzi rahimahullah',
    kunyahAr: 'أبو الفرج',
    birthAh: 510,
    birthCe: 1116,
    birthPrecision: 'approximate',
    deathAh: 597,
    deathCe: 1201,
    deathPrecision: 'year',
    specialty: ['hadith', 'tafsir', 'tarikh', 'wa\'azh'],
    madhab: 'hanbali',
    rijalGrade: 'thiqah',
    primaryLocSlug: 'baghdad',
    summaryId: 'Ulama Hanbali Baghdad yang produktif. Karya: "Zad al-Masir", "al-Muntazham", & "Shifat ash-Shafwah".',
  },
  {
    slug: 'ibn-qudamah-al-maqdisi',
    categorySlug: 'shalih_pasca_rasul',
    gender: 'male',
    nameFullAr: 'ابن قدامة المقدسي رحمه الله',
    nameFullId: 'Ibn Qudamah al-Maqdisi rahimahullah',
    kunyahAr: 'أبو محمد',
    birthAh: 541,
    birthCe: 1147,
    birthPrecision: 'year',
    deathAh: 620,
    deathCe: 1223,
    deathPrecision: 'year',
    specialty: ['fiqh', 'ushul', 'aqidah'],
    madhab: 'hanbali',
    rijalGrade: 'thiqah',
    summaryId: 'Imam fiqh madzhab Hanbali. Karya: "al-Mughni" — ensiklopedia fiqh komparatif — & "Lum\'at al-I\'tiqad".',
  },
  {
    slug: 'an-nawawi',
    categorySlug: 'shalih_pasca_rasul',
    gender: 'male',
    nameFullAr: 'يحيى بن شرف النووي رحمه الله',
    nameFullId: 'Yahya bin Syaraf an-Nawawi rahimahullah',
    kunyahAr: 'أبو زكريا',
    laqabId: 'Muhyiddin',
    birthAh: 631,
    birthCe: 1233,
    birthPrecision: 'year',
    deathAh: 676,
    deathCe: 1277,
    deathPrecision: 'year',
    specialty: ['fiqh', 'hadith'],
    madhab: 'shafii',
    rijalGrade: 'thiqah',
    primaryLocSlug: 'damaskus',
    summaryId: 'Imam fiqh Syafi\'i & muhaddits. Karya: "Riyadh ash-Shalihin", "al-Arba\'in", & "Syarh Sahih Muslim".',
  },
  {
    slug: 'al-qurthubi',
    categorySlug: 'shalih_pasca_rasul',
    gender: 'male',
    nameFullAr: 'أبو عبد الله القرطبي رحمه الله',
    nameFullId: 'Abu Abdillah al-Qurthubi rahimahullah',
    kunyahAr: 'أبو عبد الله',
    birthAh: 600,
    birthCe: 1204,
    birthPrecision: 'approximate',
    deathAh: 671,
    deathCe: 1273,
    deathPrecision: 'year',
    specialty: ['tafsir', 'fiqh', 'hadith'],
    madhab: 'maliki',
    rijalGrade: 'thiqah',
    summaryId: 'Mufassir Andalusia. Karya: "al-Jami\' li-Ahkam al-Qur\'an" (Tafsir al-Qurthubi) — fokus pada ayat hukum.',
  },

  // ─── Era Ibn Taimiyyah (7-8 H) ─────────────────────────────
  {
    slug: 'ibn-taimiyyah',
    categorySlug: 'shalih_pasca_rasul',
    gender: 'male',
    nameFullAr: 'أحمد بن عبد الحليم ابن تيمية رحمه الله',
    nameFullId: 'Ahmad bin Abdul Halim Ibn Taimiyyah rahimahullah',
    kunyahAr: 'أبو العباس',
    laqabId: 'Syaikhul Islam',
    birthAh: 661,
    birthCe: 1263,
    birthPrecision: 'year',
    deathAh: 728,
    deathCe: 1328,
    deathPrecision: 'year',
    specialty: ['aqidah', 'fiqh', 'ushul', 'tafsir', 'hadith'],
    madhab: 'hanbali',
    rijalGrade: 'thiqah',
    primaryLocSlug: 'damaskus',
    summaryId: 'Syaikhul Islam, reformer aqidah & fiqh. Karya: "Majmu\' al-Fatawa" & "Minhaj as-Sunnah an-Nabawiyyah".',
  },
  {
    slug: 'ibnul-qayyim',
    categorySlug: 'shalih_pasca_rasul',
    gender: 'male',
    nameFullAr: 'محمد بن أبي بكر ابن قيم الجوزية رحمه الله',
    nameFullId: 'Muhammad bin Abu Bakr Ibnul Qayyim al-Jauziyyah rahimahullah',
    kunyahAr: 'أبو عبد الله',
    birthAh: 691,
    birthCe: 1292,
    birthPrecision: 'year',
    deathAh: 751,
    deathCe: 1350,
    deathPrecision: 'year',
    specialty: ['aqidah', 'fiqh', 'tafsir', 'tasawuf', 'tarbiyah'],
    madhab: 'hanbali',
    rijalGrade: 'thiqah',
    primaryLocSlug: 'damaskus',
    summaryId: 'Murid utama Ibn Taimiyyah. Karya: "I\'lam al-Muwaqqi\'in", "Zad al-Ma\'ad", & "Madarij as-Salikin".',
  },
  {
    slug: 'adz-dzahabi',
    categorySlug: 'shalih_pasca_rasul',
    gender: 'male',
    nameFullAr: 'محمد بن أحمد الذهبي رحمه الله',
    nameFullId: 'Muhammad bin Ahmad adz-Dzahabi rahimahullah',
    kunyahAr: 'أبو عبد الله',
    birthAh: 673,
    birthCe: 1274,
    birthPrecision: 'year',
    deathAh: 748,
    deathCe: 1348,
    deathPrecision: 'year',
    specialty: ['hadith', 'rijal', 'tarikh'],
    madhab: 'shafii',
    rijalGrade: 'thiqah',
    primaryLocSlug: 'damaskus',
    summaryId: 'Hafizh & sejarawan. Karya: "Siyar A\'lam an-Nubala\'", "Tarikh al-Islam", & "Mizan al-I\'tidal".',
  },
  {
    slug: 'ibn-katsir',
    categorySlug: 'shalih_pasca_rasul',
    gender: 'male',
    nameFullAr: 'إسماعيل بن عمر ابن كثير رحمه الله',
    nameFullId: 'Ismail bin Umar Ibn Katsir rahimahullah',
    kunyahAr: 'أبو الفداء',
    birthAh: 700,
    birthCe: 1301,
    birthPrecision: 'approximate',
    deathAh: 774,
    deathCe: 1373,
    deathPrecision: 'year',
    specialty: ['tafsir', 'hadith', 'tarikh'],
    madhab: 'shafii',
    rijalGrade: 'thiqah',
    primaryLocSlug: 'damaskus',
    summaryId: 'Mufassir & sejarawan. Karya: "Tafsir al-Qur\'an al-\'Azhim" & "al-Bidayah wan-Nihayah".',
  },

  // ─── Era setelah Ibn Taimiyyah (8-10 H) ────────────────────
  {
    slug: 'ibn-rajab',
    categorySlug: 'shalih_pasca_rasul',
    gender: 'male',
    nameFullAr: 'ابن رجب الحنبلي رحمه الله',
    nameFullId: 'Ibn Rajab al-Hanbali rahimahullah',
    kunyahAr: 'أبو الفرج',
    birthAh: 736,
    birthCe: 1335,
    birthPrecision: 'year',
    deathAh: 795,
    deathCe: 1393,
    deathPrecision: 'year',
    specialty: ['hadith', 'fiqh', 'tarbiyah'],
    madhab: 'hanbali',
    rijalGrade: 'thiqah',
    summaryId: 'Ulama Hanbali muhaddits. Karya: "Jami\' al-\'Ulum wal-Hikam", "Lathaif al-Ma\'arif", & "Fath al-Bari" (syarah).',
  },
  {
    slug: 'ibn-hajar',
    categorySlug: 'shalih_pasca_rasul',
    gender: 'male',
    nameFullAr: 'ابن حجر العسقلاني رحمه الله',
    nameFullId: 'Ibn Hajar al-Asqalani rahimahullah',
    kunyahAr: 'أبو الفضل',
    laqabId: 'Amirul Mukminin fil Hadits',
    birthAh: 773,
    birthCe: 1372,
    birthPrecision: 'year',
    deathAh: 852,
    deathCe: 1449,
    deathPrecision: 'year',
    specialty: ['hadith', 'rijal', 'fiqh', 'tarikh'],
    madhab: 'shafii',
    rijalGrade: 'thiqah',
    primaryLocSlug: 'mesir',
    summaryId: 'Hafizh terbesar abad ke-9 H. Karya: "Fath al-Bari" (syarah Bukhari), "Tahdzib at-Tahdzib", "al-Ishabah".',
  },
  {
    slug: 'al-aini',
    categorySlug: 'shalih_pasca_rasul',
    gender: 'male',
    nameFullAr: 'بدر الدين العيني رحمه الله',
    nameFullId: 'Badruddin al-Aini rahimahullah',
    kunyahAr: 'أبو محمد',
    birthAh: 762,
    birthCe: 1361,
    birthPrecision: 'year',
    deathAh: 855,
    deathCe: 1451,
    deathPrecision: 'year',
    specialty: ['hadith', 'fiqh', 'tarikh'],
    madhab: 'hanafi',
    rijalGrade: 'thiqah',
    primaryLocSlug: 'mesir',
    summaryId: 'Muhaddits & fuqaha Hanafi. Karya: "\'Umdat al-Qari" — syarah Sahih Bukhari — & "al-Binayah" syarah al-Hidayah.',
  },
  {
    slug: 'as-sakhawi',
    categorySlug: 'shalih_pasca_rasul',
    gender: 'male',
    nameFullAr: 'شمس الدين السخاوي رحمه الله',
    nameFullId: 'Syamsuddin as-Sakhawi rahimahullah',
    kunyahAr: 'أبو الخير',
    birthAh: 831,
    birthCe: 1428,
    birthPrecision: 'year',
    deathAh: 902,
    deathCe: 1497,
    deathPrecision: 'year',
    specialty: ['hadith', 'rijal', 'tarikh'],
    madhab: 'shafii',
    rijalGrade: 'thiqah',
    summaryId: 'Murid Ibn Hajar al-Asqalani. Karya: "adh-Dhau\' al-Lami\'" — biografi tokoh abad ke-9 H — & "Fath al-Mughits".',
  },
  {
    slug: 'as-suyuthi',
    categorySlug: 'shalih_pasca_rasul',
    gender: 'male',
    nameFullAr: 'جلال الدين السيوطي رحمه الله',
    nameFullId: 'Jalaluddin as-Suyuthi rahimahullah',
    kunyahAr: 'أبو الفضل',
    birthAh: 849,
    birthCe: 1445,
    birthPrecision: 'year',
    deathAh: 911,
    deathCe: 1505,
    deathPrecision: 'year',
    specialty: ['tafsir', 'hadith', 'fiqh', 'tarikh', 'lughah'],
    madhab: 'shafii',
    rijalGrade: 'thiqah',
    primaryLocSlug: 'mesir',
    summaryId: 'Polimat produktif (>500 karya). Karya: "Tafsir al-Jalalain", "al-Itqan", & "al-Jami\' ash-Shaghir".',
  },

  // ─── Era Modern (12-15 H) ──────────────────────────────────
  {
    slug: 'ash-shanani',
    categorySlug: 'shalih_pasca_rasul',
    gender: 'male',
    nameFullAr: 'محمد بن إسماعيل الصنعاني رحمه الله',
    nameFullId: "Muhammad bin Ismail ash-Shan'ani rahimahullah",
    kunyahAr: 'أبو إبراهيم',
    birthAh: 1099,
    birthCe: 1688,
    birthPrecision: 'year',
    deathAh: 1182,
    deathCe: 1768,
    deathPrecision: 'year',
    specialty: ['hadith', 'fiqh', 'ushul'],
    madhab: 'no_madhab',
    rijalGrade: 'thiqah',
    summaryId: "Ulama Yaman, ahli hadits. Karya: \"Subul as-Salam\" — syarah Bulughul Maram karya Ibn Hajar.",
  },
  {
    slug: 'muhammad-bin-abdul-wahhab',
    categorySlug: 'shalih_pasca_rasul',
    gender: 'male',
    nameFullAr: 'محمد بن عبد الوهاب رحمه الله',
    nameFullId: 'Muhammad bin Abdul Wahhab rahimahullah',
    kunyahAr: 'أبو الحسين',
    birthAh: 1115,
    birthCe: 1703,
    birthPrecision: 'year',
    deathAh: 1206,
    deathCe: 1792,
    deathPrecision: 'year',
    specialty: ['aqidah', 'fiqh', 'tafsir'],
    madhab: 'hanbali',
    rijalGrade: 'not_narrator',
    summaryId: 'Pemimpin dakwah pemurnian tauhid di Najd. Karya: "Kitab at-Tauhid", "Ushul ats-Tsalatsah", & "Kasyf asy-Syubuhat".',
  },
  {
    slug: 'asy-syaukani',
    categorySlug: 'shalih_pasca_rasul',
    gender: 'male',
    nameFullAr: 'محمد بن علي الشوكاني رحمه الله',
    nameFullId: 'Muhammad bin Ali asy-Syaukani rahimahullah',
    kunyahAr: 'أبو عبد الله',
    birthAh: 1173,
    birthCe: 1759,
    birthPrecision: 'year',
    deathAh: 1250,
    deathCe: 1834,
    deathPrecision: 'year',
    specialty: ['hadith', 'fiqh', 'ushul', 'tafsir'],
    madhab: 'no_madhab',
    rijalGrade: 'thiqah',
    summaryId: 'Mujtahid Yaman. Karya: "Nail al-Authar", "Fath al-Qadir" (tafsir), & "Irsyad al-Fuhul" (ushul fiqh).',
  },
  {
    slug: 'siddiq-hasan-khan',
    categorySlug: 'shalih_pasca_rasul',
    gender: 'male',
    nameFullAr: 'صديق حسن خان القنوجي رحمه الله',
    nameFullId: 'Siddiq Hasan Khan al-Qannuji rahimahullah',
    kunyahAr: 'أبو الطيب',
    birthAh: 1248,
    birthCe: 1832,
    birthPrecision: 'year',
    deathAh: 1307,
    deathCe: 1890,
    deathPrecision: 'year',
    specialty: ['hadith', 'fiqh', 'tafsir'],
    madhab: 'no_madhab',
    rijalGrade: 'not_narrator',
    summaryId: 'Ulama Ahli Hadits India (Bhopal). Karya: "Fath al-Bayan", "ar-Raudhah an-Nadiyyah", & "Abjad al-\'Ulum".',
  },
  {
    slug: 'bin-baz',
    categorySlug: 'shalih_pasca_rasul',
    gender: 'male',
    nameFullAr: 'عبد العزيز بن باز رحمه الله',
    nameFullId: 'Abdul Aziz bin Abdullah bin Baz rahimahullah',
    kunyahAr: 'أبو عبد الله',
    birthAh: 1330,
    birthCe: 1912,
    birthPrecision: 'year',
    deathAh: 1420,
    deathCe: 1999,
    deathPrecision: 'year',
    specialty: ['fiqh', 'aqidah', 'fatwa', 'hadith'],
    madhab: 'hanbali',
    rijalGrade: 'not_narrator',
    summaryId: 'Mufti besar Kerajaan Arab Saudi & ketua Hai\'ah Kibar al-\'Ulama\'. Karya: "Majmu\' Fatawa Ibn Baz".',
  },
  {
    slug: 'al-albani',
    categorySlug: 'shalih_pasca_rasul',
    gender: 'male',
    nameFullAr: 'محمد ناصر الدين الألباني رحمه الله',
    nameFullId: 'Muhammad Nashiruddin al-Albani rahimahullah',
    kunyahAr: 'أبو عبد الرحمن',
    birthAh: 1333,
    birthCe: 1914,
    birthPrecision: 'year',
    deathAh: 1420,
    deathCe: 1999,
    deathPrecision: 'year',
    specialty: ['hadith', 'rijal', 'fiqh'],
    madhab: 'no_madhab',
    rijalGrade: 'thiqah',
    summaryId: 'Muhaddits abad ke-20. Karya: "Silsilat al-Ahadits ash-Shahihah & adh-Dha\'ifah" serta tahqiq Sunan Empat.',
  },
  {
    slug: 'ibn-utsaimin',
    categorySlug: 'shalih_pasca_rasul',
    gender: 'male',
    nameFullAr: 'محمد بن صالح العثيمين رحمه الله',
    nameFullId: "Muhammad bin Shalih al-'Utsaimin rahimahullah",
    kunyahAr: 'أبو عبد الله',
    birthAh: 1347,
    birthCe: 1929,
    birthPrecision: 'year',
    deathAh: 1421,
    deathCe: 2001,
    deathPrecision: 'year',
    specialty: ['fiqh', 'aqidah', 'tafsir', 'fatwa'],
    madhab: 'hanbali',
    rijalGrade: 'not_narrator',
    summaryId: 'Anggota Hai\'ah Kibar al-\'Ulama\' Saudi. Karya: "Syarh al-Mumti\'", "Syarh Riyadh ash-Shalihin", & ratusan fatwa.',
  },

  // ─── Ulama wanita pasca-salaf ──────────────────────────────
  {
    slug: 'karimah-al-marwaziyyah',
    categorySlug: 'shalih_pasca_rasul',
    gender: 'female',
    nameFullAr: 'كريمة بنت أحمد المروزية رحمها الله',
    nameFullId: 'Karimah binti Ahmad al-Marwaziyyah rahimahallah',
    kunyahAr: 'أم الكرام',
    birthAh: 365,
    birthCe: 975,
    birthPrecision: 'approximate',
    deathAh: 463,
    deathCe: 1071,
    deathPrecision: 'year',
    specialty: ['hadith'],
    rijalGrade: 'thiqah',
    primaryLocSlug: 'makkah',
    summaryId: 'Muhadditsah Mekkah, perawi utama Sahih Bukhari di zamannya. Banyak ulama besar menyimak Bukhari darinya.',
  },
  {
    slug: 'fathimah-al-jurjaniyyah',
    categorySlug: 'shalih_pasca_rasul',
    gender: 'female',
    nameFullAr: 'فاطمة بنت أبي الحسن الجرجانية رحمها الله',
    nameFullId: "Fathimah binti Abi al-Hasan al-Jurjaniyyah rahimahallah",
    deathAh: 480,
    deathCe: 1087,
    deathPrecision: 'approximate',
    specialty: ['hadith'],
    rijalGrade: 'thiqah',
    summaryId: 'Muhadditsah Jurjan abad ke-5 H. Perawi yang diakui dalam isnad ulama Khurasan & \'Iraq.',
  },
]

export async function seed025UlamaPascaSalaf() {
  const db = getSeedDb()
  const cats = await db.select().from(figureCategories)
  const catBySlug = new Map(cats.map((c) => [c.slug, c.id]))
  const locs = await db.select().from(locations)
  const locBySlug = new Map(locs.map((l) => [l.slug, l.id]))

  let total = 0
  for (const f of FIGURES) {
    const categoryId = catBySlug.get(f.categorySlug)
    if (!categoryId) continue
    const primaryLocationId = f.primaryLocSlug ? locBySlug.get(f.primaryLocSlug) : undefined
    const result = await db
      .insert(figures)
      .values({
        slug: f.slug,
        categoryId,
        gender: f.gender,
        nameFullAr: f.nameFullAr,
        nameFullId: f.nameFullId,
        kunyahAr: f.kunyahAr,
        laqabId: f.laqabId,
        birthDateAh: f.birthAh,
        birthDateCe: f.birthCe,
        birthDatePrecision: f.birthPrecision,
        deathDateAh: f.deathAh,
        deathDateCe: f.deathCe,
        deathDatePrecision: f.deathPrecision,
        specialty: f.specialty,
        madhab: f.madhab,
        rijalGrade: f.rijalGrade ?? 'unverified',
        primaryLocationId,
        summaryId: f.summaryId,
        status: 'published',
        publishedAt: new Date(),
      })
      .onConflictDoNothing()
      .returning()
    if (result.length > 0) total++
  }
  logSeed('ulama_pasca_salaf', total)
}
